spring:
  http:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 1024Mb
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/bookexchange?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: bookexchange
    password: bookexchange
